name: bench

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  schedule:
    - cron: '0 9 * * 4'
  workflow_dispatch:

jobs:
  test:
    name: bench-${{matrix.distribution}}-${{matrix.version}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name:
          - jdk8
          - jdk11
        include:
          - name: jdk8
            version: 8
            distribution: temurin
          - name: jdk11
            version: 11
            distribution: temurin
          - name: jdk16
            version: 16
            distribution: temurin
          - name: jdk17
            version: 17
            distribution: temurin
    steps:
      - name: checkout-${{matrix.name}}
        uses: actions/checkout@v2
      - name: setup-toolchain-${{matrix.name}}
        uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.version}}
          distribution: ${{matrix.distribution}}
          cache: maven
      - name: build-${{matrix.name}}
        run: mvn -P benchmark clean package -B -V
      - name: benchmark-${{matrix.name}}
        run: java -jar target/benchmark.jar AzamCodecBench -rf json
      - name: upload-bench-results-${{matrix.name}}
        uses: actions/upload-artifact@v1
        with:
          name: azamcodec_bench_${{matrix.name}}_${{github.sha}}
          path: ./jmh-result.json
